package com.smarthome.hume.core.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * M3E theme seeds port tu demo HTML (hume-m3e-v4-dashboard.html).
 * Seed doi ca primary family + neutrals (tonal spot) — khong chi accent.
 * Gen tu: goals/hume-android-app-code-updates/hidden_files/m3e-port/m3e_theme_tokens.json
 * (tertiary* chi co o seed cam -> cac seed khac fallback ve primary family)
 */
enum class M3ESeed { Cam, Green, Blue, Violet, Red, Pink, Teal, Amber }

private val lightSchemeCam: ColorScheme
    get() = lightColorScheme(
        primary = Color(0xFFF9784C),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFD9C7),
        onPrimaryContainer = Color(0xFF6B2208),
        secondary = Color(0xFF6E5B45),
        secondaryContainer = Color(0xFFEDE3D2),
        onSecondaryContainer = Color(0xFF251B0F),
        tertiary = Color(0xFFF2D26F),
        tertiaryContainer = Color(0xFFFBEFC3),
        onTertiaryContainer = Color(0xFF5C4A08),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        surface = Color(0xFFE7E5E2),
        onSurface = Color(0xFF191412),
        surfaceContainerLowest = Color(0xFFF4F2EF),
        surfaceContainerLow = Color(0xFFECEAE7),
        surfaceContainer = Color(0xFFEFEDEA),
        surfaceContainerHigh = Color(0xFFF6F4F1),
        surfaceContainerHighest = Color(0xFFFFFFFF),
        inverseSurface = Color(0xFF322F2B),
        inverseOnSurface = Color(0xFFF5F0E9),
        inversePrimary = Color(0xFFFFB59D),
        outline = Color(0xFFD9CFC4),
        outlineVariant = Color(0xFFE9E2D7),
        scrim = Color(0x73191412),
        onSecondary = Color(0xFFFFFFFF),
        onTertiary = Color(0xFFFFFFFF),
        surfaceVariant = Color(0xFFEFEDEA),
        onSurfaceVariant = Color(0xFF6F5F54),
    )

private val darkSchemeCam: ColorScheme
    get() = darkColorScheme(
        primary = Color(0xFFFFB59D),
        onPrimary = Color(0xFF5C1A00),
        primaryContainer = Color(0xFF7A2E14),
        onPrimaryContainer = Color(0xFFFFD9C7),
        secondary = Color(0xFFD2C2A6),
        secondaryContainer = Color(0xFF4C4232),
        onSecondaryContainer = Color(0xFFF6EEDE),
        tertiary = Color(0xFFF2D26F),
        tertiaryContainer = Color(0xFF5C4A08),
        onTertiaryContainer = Color(0xFFFBEFC3),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        surface = Color(0xFF141210),
        onSurface = Color(0xFFF2E9E1),
        surfaceContainerLowest = Color(0xFF28211B),
        surfaceContainerLow = Color(0xFF1A1714),
        surfaceContainer = Color(0xFF221D18),
        surfaceContainerHigh = Color(0xFF2A241E),
        surfaceContainerHighest = Color(0xFF35302A),
        inverseSurface = Color(0xFFE9E1D8),
        inverseOnSurface = Color(0xFF1D1B16),
        inversePrimary = Color(0xFF7A2E14),
        outline = Color(0xFF4A4239),
        outlineVariant = Color(0xFF38322B),
        scrim = Color(0x99000000),
        onSecondary = Color(0xFF5C1A00),
        onTertiary = Color(0xFF5C1A00),
        surfaceVariant = Color(0xFF221D18),
        onSurfaceVariant = Color(0xFFB8A898),
    )

private val lightSchemeGreen: ColorScheme
    get() = lightColorScheme(
        primary = Color(0xFF478A4D),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFCFF0D2),
        onPrimaryContainer = Color(0xFF0C3A12),
        secondary = Color(0xFF5C6B4A),
        secondaryContainer = Color(0xFFE0E9D0),
        onSecondaryContainer = Color(0xFF1C2510),
        tertiary = Color(0xFF478A4D),
        tertiaryContainer = Color(0xFFCFF0D2),
        onTertiaryContainer = Color(0xFF0C3A12),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        surface = Color(0xFFD6DED4),
        onSurface = Color(0xFF191D19),
        surfaceContainerLowest = Color(0xFFF7F8F6),
        surfaceContainerLow = Color(0xFFEFF2EE),
        surfaceContainer = Color(0xFFEDF0EC),
        surfaceContainerHigh = Color(0xFFF2F4F1),
        surfaceContainerHighest = Color(0xFFFFFFFF),
        inverseSurface = Color(0xFF2C332C),
        inverseOnSurface = Color(0xFF478A4D),
        inversePrimary = Color(0xFF9BDBA2),
        outline = Color(0xFF72796E),
        outlineVariant = Color(0xFFC1C9BE),
        scrim = Color(0xFF478A4D),
        onSecondary = Color(0xFFFFFFFF),
        onTertiary = Color(0xFFFFFFFF),
        surfaceVariant = Color(0xFFEDF0EC),
        onSurfaceVariant = Color(0xFF414941),
    )

private val darkSchemeGreen: ColorScheme
    get() = darkColorScheme(
        primary = Color(0xFF9BDBA2),
        onPrimary = Color(0xFF0C3A12),
        primaryContainer = Color(0xFF2A5A30),
        onPrimaryContainer = Color(0xFFCFF0D2),
        secondary = Color(0xFFBCCBA4),
        secondaryContainer = Color(0xFF3C4830),
        onSecondaryContainer = Color(0xFFE9F1DA),
        tertiary = Color(0xFF9BDBA2),
        tertiaryContainer = Color(0xFF2A5A30),
        onTertiaryContainer = Color(0xFFCFF0D2),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        surface = Color(0xFF101410),
        onSurface = Color(0xFFE1E6DE),
        surfaceContainerLowest = Color(0xFF1E251E),
        surfaceContainerLow = Color(0xFF161B16),
        surfaceContainer = Color(0xFF1C221C),
        surfaceContainerHigh = Color(0xFF272D27),
        surfaceContainerHighest = Color(0xFF323833),
        inverseSurface = Color(0xFFE1E6DE),
        inverseOnSurface = Color(0xFF9BDBA2),
        inversePrimary = Color(0xFF2A5A30),
        outline = Color(0xFF8B938A),
        outlineVariant = Color(0xFF3A4038),
        scrim = Color(0xFF9BDBA2),
        onSecondary = Color(0xFF0C3A12),
        onTertiary = Color(0xFF0C3A12),
        surfaceVariant = Color(0xFF1C221C),
        onSurfaceVariant = Color(0xFFA7B0A2),
    )

private val lightSchemeBlue: ColorScheme
    get() = lightColorScheme(
        primary = Color(0xFF2F6EA3),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFD3E9F8),
        onPrimaryContainer = Color(0xFF0A3352),
        secondary = Color(0xFF5A6072),
        secondaryContainer = Color(0xFFDEE2EC),
        onSecondaryContainer = Color(0xFF1A1D26),
        tertiary = Color(0xFF2F6EA3),
        tertiaryContainer = Color(0xFFD3E9F8),
        onTertiaryContainer = Color(0xFF0A3352),
        error = Color(0xFF2F6EA3),
        onError = Color(0xFF2F6EA3),
        errorContainer = Color(0xFF2F6EA3),
        onErrorContainer = Color(0xFF2F6EA3),
        surface = Color(0xFFD4DCE6),
        onSurface = Color(0xFF191C20),
        surfaceContainerLowest = Color(0xFFF6F8FA),
        surfaceContainerLow = Color(0xFFEEF1F5),
        surfaceContainer = Color(0xFFECEFF4),
        surfaceContainerHigh = Color(0xFFF1F4F7),
        surfaceContainerHighest = Color(0xFFFFFFFF),
        inverseSurface = Color(0xFF2E3135),
        inverseOnSurface = Color(0xFF2F6EA3),
        inversePrimary = Color(0xFF9CCCF5),
        outline = Color(0xFF72787E),
        outlineVariant = Color(0xFFC1C7CE),
        scrim = Color(0xFF2F6EA3),
        onSecondary = Color(0xFFFFFFFF),
        onTertiary = Color(0xFFFFFFFF),
        surfaceVariant = Color(0xFFECEFF4),
        onSurfaceVariant = Color(0xFF41474D),
    )

private val darkSchemeBlue: ColorScheme
    get() = darkColorScheme(
        primary = Color(0xFF9CCCF5),
        onPrimary = Color(0xFF0A3352),
        primaryContainer = Color(0xFF1E4A6E),
        onPrimaryContainer = Color(0xFFD3E9F8),
        secondary = Color(0xFFBFC6D4),
        secondaryContainer = Color(0xFF3A3F49),
        onSecondaryContainer = Color(0xFFE6EAF2),
        tertiary = Color(0xFF9CCCF5),
        tertiaryContainer = Color(0xFF1E4A6E),
        onTertiaryContainer = Color(0xFFD3E9F8),
        error = Color(0xFF9CCCF5),
        onError = Color(0xFF9CCCF5),
        errorContainer = Color(0xFF9CCCF5),
        onErrorContainer = Color(0xFF9CCCF5),
        surface = Color(0xFF0F1419),
        onSurface = Color(0xFFE1E6EB),
        surfaceContainerLowest = Color(0xFF1F262D),
        surfaceContainerLow = Color(0xFF151B21),
        surfaceContainer = Color(0xFF1B2229),
        surfaceContainerHigh = Color(0xFF262E36),
        surfaceContainerHighest = Color(0xFF313A43),
        inverseSurface = Color(0xFFE1E6EB),
        inverseOnSurface = Color(0xFF9CCCF5),
        inversePrimary = Color(0xFF1E4A6E),
        outline = Color(0xFF8A9198),
        outlineVariant = Color(0xFF394047),
        scrim = Color(0xFF9CCCF5),
        onSecondary = Color(0xFF0A3352),
        onTertiary = Color(0xFF0A3352),
        surfaceVariant = Color(0xFF1B2229),
        onSurfaceVariant = Color(0xFFA4ABB3),
    )

private val lightSchemeViolet: ColorScheme
    get() = lightColorScheme(
        primary = Color(0xFF6A54A6),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFE7E0F7),
        onPrimaryContainer = Color(0xFF2E2156),
        secondary = Color(0xFF655A72),
        secondaryContainer = Color(0xFFE6E0F2),
        onSecondaryContainer = Color(0xFF221B2D),
        tertiary = Color(0xFF6A54A6),
        tertiaryContainer = Color(0xFFE7E0F7),
        onTertiaryContainer = Color(0xFF2E2156),
        error = Color(0xFF6A54A6),
        onError = Color(0xFF6A54A6),
        errorContainer = Color(0xFF6A54A6),
        onErrorContainer = Color(0xFF6A54A6),
        surface = Color(0xFFD8D3E5),
        onSurface = Color(0xFF1B1A21),
        surfaceContainerLowest = Color(0xFFF7F6FA),
        surfaceContainerLow = Color(0xFFEFEDF5),
        surfaceContainer = Color(0xFFEDEBF3),
        surfaceContainerHigh = Color(0xFFF3F1F7),
        surfaceContainerHighest = Color(0xFFFFFFFF),
        inverseSurface = Color(0xFF302F36),
        inverseOnSurface = Color(0xFF6A54A6),
        inversePrimary = Color(0xFFC9B8F2),
        outline = Color(0xFF777680),
        outlineVariant = Color(0xFFCAC5D6),
        scrim = Color(0xFF6A54A6),
        onSecondary = Color(0xFFFFFFFF),
        onTertiary = Color(0xFFFFFFFF),
        surfaceVariant = Color(0xFFEDEBF3),
        onSurfaceVariant = Color(0xFF474654),
    )

private val darkSchemeViolet: ColorScheme
    get() = darkColorScheme(
        primary = Color(0xFFC9B8F2),
        onPrimary = Color(0xFF2E2156),
        primaryContainer = Color(0xFF4A3A7A),
        onPrimaryContainer = Color(0xFFE7E0F7),
        secondary = Color(0xFFC9BEDC),
        secondaryContainer = Color(0xFF453C53),
        onSecondaryContainer = Color(0xFFEDE8F8),
        tertiary = Color(0xFFC9B8F2),
        tertiaryContainer = Color(0xFF4A3A7A),
        onTertiaryContainer = Color(0xFFE7E0F7),
        error = Color(0xFFC9B8F2),
        onError = Color(0xFFC9B8F2),
        errorContainer = Color(0xFFC9B8F2),
        onErrorContainer = Color(0xFFC9B8F2),
        surface = Color(0xFF121016),
        onSurface = Color(0xFFE6E3EA),
        surfaceContainerLowest = Color(0xFF242131),
        surfaceContainerLow = Color(0xFF17141D),
        surfaceContainer = Color(0xFF1E1A25),
        surfaceContainerHigh = Color(0xFF282431),
        surfaceContainerHighest = Color(0xFF343043),
        inverseSurface = Color(0xFFE6E3EA),
        inverseOnSurface = Color(0xFFC9B8F2),
        inversePrimary = Color(0xFF4A3A7A),
        outline = Color(0xFF8F8C97),
        outlineVariant = Color(0xFF3C3945),
        scrim = Color(0xFFC9B8F2),
        onSecondary = Color(0xFF2E2156),
        onTertiary = Color(0xFF2E2156),
        surfaceVariant = Color(0xFF1E1A25),
        onSurfaceVariant = Color(0xFFA9A6B1),
    )

private val lightSchemeRed: ColorScheme
    get() = lightColorScheme(
        primary = Color(0xFFBE4130),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFDAD4),
        onPrimaryContainer = Color(0xFF5C1510),
        secondary = Color(0xFF775651),
        secondaryContainer = Color(0xFFF5DDD8),
        onSecondaryContainer = Color(0xFF2C1512),
        tertiary = Color(0xFFBE4130),
        tertiaryContainer = Color(0xFFFFDAD4),
        onTertiaryContainer = Color(0xFF5C1510),
        error = Color(0xFFBE4130),
        onError = Color(0xFFBE4130),
        errorContainer = Color(0xFFBE4130),
        onErrorContainer = Color(0xFFBE4130),
        surface = Color(0xFFE0D5D0),
        onSurface = Color(0xFF1F1B1A),
        surfaceContainerLowest = Color(0xFFF9F7F6),
        surfaceContainerLow = Color(0xFFF3EEEC),
        surfaceContainer = Color(0xFFF1ECEA),
        surfaceContainerHigh = Color(0xFFF5F2F0),
        surfaceContainerHighest = Color(0xFFFFFFFF),
        inverseSurface = Color(0xFF362F2D),
        inverseOnSurface = Color(0xFFBE4130),
        inversePrimary = Color(0xFFFFB4A5),
        outline = Color(0xFF85736F),
        outlineVariant = Color(0xFFD8C2BC),
        scrim = Color(0xFFBE4130),
        onSecondary = Color(0xFFFFFFFF),
        onTertiary = Color(0xFFFFFFFF),
        surfaceVariant = Color(0xFFF1ECEA),
        onSurfaceVariant = Color(0xFF534341),
    )

private val darkSchemeRed: ColorScheme
    get() = darkColorScheme(
        primary = Color(0xFFFFB4A5),
        onPrimary = Color(0xFF680003),
        primaryContainer = Color(0xFF7A1F16),
        onPrimaryContainer = Color(0xFFFFDAD4),
        secondary = Color(0xFFE7BDB6),
        secondaryContainer = Color(0xFF5D3F3A),
        onSecondaryContainer = Color(0xFFF5DDD8),
        tertiary = Color(0xFFFFB4A5),
        tertiaryContainer = Color(0xFF7A1F16),
        onTertiaryContainer = Color(0xFFFFDAD4),
        error = Color(0xFFFFB4A5),
        onError = Color(0xFFFFB4A5),
        errorContainer = Color(0xFFFFB4A5),
        onErrorContainer = Color(0xFFFFB4A5),
        surface = Color(0xFF171212),
        onSurface = Color(0xFFF5E9E6),
        surfaceContainerLowest = Color(0xFF2A2220),
        surfaceContainerLow = Color(0xFF1E1917),
        surfaceContainer = Color(0xFF251E1C),
        surfaceContainerHigh = Color(0xFF2E2624),
        surfaceContainerHighest = Color(0xFF3A322F),
        inverseSurface = Color(0xFFF5E9E6),
        inverseOnSurface = Color(0xFFFFB4A5),
        inversePrimary = Color(0xFFBE4130),
        outline = Color(0xFF9A8480),
        outlineVariant = Color(0xFF453B38),
        scrim = Color(0xFFFFB4A5),
        onSecondary = Color(0xFF680003),
        onTertiary = Color(0xFF680003),
        surfaceVariant = Color(0xFF251E1C),
        onSurfaceVariant = Color(0xFFD8BFB9),
    )

private val lightSchemePink: ColorScheme
    get() = lightColorScheme(
        primary = Color(0xFF9E3D6E),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFF9DCE8),
        onPrimaryContainer = Color(0xFF5C0E2E),
        secondary = Color(0xFF6E5560),
        secondaryContainer = Color(0xFFF2DCE4),
        onSecondaryContainer = Color(0xFF281620),
        tertiary = Color(0xFF9E3D6E),
        tertiaryContainer = Color(0xFFF9DCE8),
        onTertiaryContainer = Color(0xFF5C0E2E),
        error = Color(0xFF9E3D6E),
        onError = Color(0xFF9E3D6E),
        errorContainer = Color(0xFF9E3D6E),
        onErrorContainer = Color(0xFF9E3D6E),
        surface = Color(0xFFE0D4DB),
        onSurface = Color(0xFF201A1E),
        surfaceContainerLowest = Color(0xFFF9F6F8),
        surfaceContainerLow = Color(0xFFF3EEF1),
        surfaceContainer = Color(0xFFF1ECEF),
        surfaceContainerHigh = Color(0xFFF5F1F3),
        surfaceContainerHighest = Color(0xFFFFFFFF),
        inverseSurface = Color(0xFF352F33),
        inverseOnSurface = Color(0xFF9E3D6E),
        inversePrimary = Color(0xFFF0A8C8),
        outline = Color(0xFF7E747B),
        outlineVariant = Color(0xFFD6C9D1),
        scrim = Color(0xFF9E3D6E),
        onSecondary = Color(0xFFFFFFFF),
        onTertiary = Color(0xFFFFFFFF),
        surfaceVariant = Color(0xFFF1ECEF),
        onSurfaceVariant = Color(0xFF4F444B),
    )

private val darkSchemePink: ColorScheme
    get() = darkColorScheme(
        primary = Color(0xFFF0A8C8),
        onPrimary = Color(0xFF5C0E2E),
        primaryContainer = Color(0xFF7A2A52),
        onPrimaryContainer = Color(0xFFF9DCE8),
        secondary = Color(0xFFD3BDC7),
        secondaryContainer = Color(0xFF4E3A44),
        onSecondaryContainer = Color(0xFFF2DCE4),
        tertiary = Color(0xFFF0A8C8),
        tertiaryContainer = Color(0xFF7A2A52),
        onTertiaryContainer = Color(0xFFF9DCE8),
        error = Color(0xFFF0A8C8),
        onError = Color(0xFFF0A8C8),
        errorContainer = Color(0xFFF0A8C8),
        onErrorContainer = Color(0xFFF0A8C8),
        surface = Color(0xFF161215),
        onSurface = Color(0xFFF0E6EB),
        surfaceContainerLowest = Color(0xFF281E24),
        surfaceContainerLow = Color(0xFF1C171B),
        surfaceContainer = Color(0xFF231C21),
        surfaceContainerHigh = Color(0xFF2D252B),
        surfaceContainerHighest = Color(0xFF3A3238),
        inverseSurface = Color(0xFFF0E6EB),
        inverseOnSurface = Color(0xFFF0A8C8),
        inversePrimary = Color(0xFF9E3D6E),
        outline = Color(0xFF978A93),
        outlineVariant = Color(0xFF443C43),
        scrim = Color(0xFFF0A8C8),
        onSecondary = Color(0xFF5C0E2E),
        onTertiary = Color(0xFF5C0E2E),
        surfaceVariant = Color(0xFF231C21),
        onSurfaceVariant = Color(0xFFCDBFC7),
    )

private val lightSchemeTeal: ColorScheme
    get() = lightColorScheme(
        primary = Color(0xFF2A7F76),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFBCE9E2),
        onPrimaryContainer = Color(0xFF073B36),
        secondary = Color(0xFF4C6663),
        secondaryContainer = Color(0xFFCEE8E4),
        onSecondaryContainer = Color(0xFF0E2422),
        tertiary = Color(0xFF2A7F76),
        tertiaryContainer = Color(0xFFBCE9E2),
        onTertiaryContainer = Color(0xFF073B36),
        error = Color(0xFF2A7F76),
        onError = Color(0xFF2A7F76),
        errorContainer = Color(0xFF2A7F76),
        onErrorContainer = Color(0xFF2A7F76),
        surface = Color(0xFFD3DFDE),
        onSurface = Color(0xFF171D1C),
        surfaceContainerLowest = Color(0xFFF6F9F8),
        surfaceContainerLow = Color(0xFFEDF2F2),
        surfaceContainer = Color(0xFFEBF1F0),
        surfaceContainerHigh = Color(0xFFF1F5F4),
        surfaceContainerHighest = Color(0xFFFFFFFF),
        inverseSurface = Color(0xFF2B3231),
        inverseOnSurface = Color(0xFF2A7F76),
        inversePrimary = Color(0xFFA8D8D1),
        outline = Color(0xFF6F7978),
        outlineVariant = Color(0xFFBEC9C8),
        scrim = Color(0xFF2A7F76),
        onSecondary = Color(0xFFFFFFFF),
        onTertiary = Color(0xFFFFFFFF),
        surfaceVariant = Color(0xFFEBF1F0),
        onSurfaceVariant = Color(0xFF3F4948),
    )

private val darkSchemeTeal: ColorScheme
    get() = darkColorScheme(
        primary = Color(0xFFA8D8D1),
        onPrimary = Color(0xFF073B36),
        primaryContainer = Color(0xFF1F5A54),
        onPrimaryContainer = Color(0xFFBCE9E2),
        secondary = Color(0xFFB0CCC8),
        secondaryContainer = Color(0xFF334E4B),
        onSecondaryContainer = Color(0xFFCEE8E4),
        tertiary = Color(0xFFA8D8D1),
        tertiaryContainer = Color(0xFF1F5A54),
        onTertiaryContainer = Color(0xFFBCE9E2),
        error = Color(0xFFA8D8D1),
        onError = Color(0xFFA8D8D1),
        errorContainer = Color(0xFFA8D8D1),
        onErrorContainer = Color(0xFFA8D8D1),
        surface = Color(0xFF0E1514),
        onSurface = Color(0xFFDEE6E5),
        surfaceContainerLowest = Color(0xFF1D2625),
        surfaceContainerLow = Color(0xFF141B1A),
        surfaceContainer = Color(0xFF1A2221),
        surfaceContainerHigh = Color(0xFF242E2D),
        surfaceContainerHighest = Color(0xFF2F3A39),
        inverseSurface = Color(0xFFDEE6E5),
        inverseOnSurface = Color(0xFFA8D8D1),
        inversePrimary = Color(0xFF2A7F76),
        outline = Color(0xFF889392),
        outlineVariant = Color(0xFF363F3E),
        scrim = Color(0xFFA8D8D1),
        onSecondary = Color(0xFF073B36),
        onTertiary = Color(0xFF073B36),
        surfaceVariant = Color(0xFF1A2221),
        onSurfaceVariant = Color(0xFFA2ADAC),
    )

private val lightSchemeAmber: ColorScheme
    get() = lightColorScheme(
        primary = Color(0xFF776000),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFBEFC3),
        onPrimaryContainer = Color(0xFF5C4A08),
        secondary = Color(0xFF6B5D3F),
        secondaryContainer = Color(0xFFF5E8CF),
        onSecondaryContainer = Color(0xFF241A04),
        tertiary = Color(0xFF776000),
        tertiaryContainer = Color(0xFFFBEFC3),
        onTertiaryContainer = Color(0xFF5C4A08),
        error = Color(0xFF776000),
        onError = Color(0xFF776000),
        errorContainer = Color(0xFF776000),
        onErrorContainer = Color(0xFF776000),
        surface = Color(0xFFDDD5C2),
        onSurface = Color(0xFF1D1B16),
        surfaceContainerLowest = Color(0xFFF8F7F3),
        surfaceContainerLow = Color(0xFFF1EEE7),
        surfaceContainer = Color(0xFFF0ECE4),
        surfaceContainerHigh = Color(0xFFF4F2EB),
        surfaceContainerHighest = Color(0xFFFFFFFF),
        inverseSurface = Color(0xFF33302A),
        inverseOnSurface = Color(0xFF776000),
        inversePrimary = Color(0xFFE8C547),
        outline = Color(0xFF7D7667),
        outlineVariant = Color(0xFFD5CDB8),
        scrim = Color(0xFF776000),
        onSecondary = Color(0xFFFFFFFF),
        onTertiary = Color(0xFFFFFFFF),
        surfaceVariant = Color(0xFFF0ECE4),
        onSurfaceVariant = Color(0xFF4C4639),
    )

private val darkSchemeAmber: ColorScheme
    get() = darkColorScheme(
        primary = Color(0xFFE8C547),
        onPrimary = Color(0xFF3A2E00),
        primaryContainer = Color(0xFF5C4A08),
        onPrimaryContainer = Color(0xFFFBEFC3),
        secondary = Color(0xFFD2C49D),
        secondaryContainer = Color(0xFF4A4132),
        onSecondaryContainer = Color(0xFFF5E8CF),
        tertiary = Color(0xFFE8C547),
        tertiaryContainer = Color(0xFF5C4A08),
        onTertiaryContainer = Color(0xFFFBEFC3),
        error = Color(0xFFE8C547),
        onError = Color(0xFFE8C547),
        errorContainer = Color(0xFFE8C547),
        onErrorContainer = Color(0xFFE8C547),
        surface = Color(0xFF14120C),
        onSurface = Color(0xFFEDE8DC),
        surfaceContainerLowest = Color(0xFF262219),
        surfaceContainerLow = Color(0xFF1A1712),
        surfaceContainer = Color(0xFF201C14),
        surfaceContainerHigh = Color(0xFF2A251B),
        surfaceContainerHighest = Color(0xFF363024),
        inverseSurface = Color(0xFFEDE8DC),
        inverseOnSurface = Color(0xFFE8C547),
        inversePrimary = Color(0xFF776000),
        outline = Color(0xFF99917D),
        outlineVariant = Color(0xFF403A2E),
        scrim = Color(0xFFE8C547),
        onSecondary = Color(0xFF3A2E00),
        onTertiary = Color(0xFF3A2E00),
        surfaceVariant = Color(0xFF201C14),
        onSurfaceVariant = Color(0xFFBDB5A2),
    )


internal fun colorSchemeFor(seed: M3ESeed, dark: Boolean): ColorScheme {
    val s = seed.name.lowercase()
    return when {
        dark && s == "cam" -> darkSchemeCam
        s == "cam" -> lightSchemeCam
        dark && s == "green" -> darkSchemeGreen
        s == "green" -> lightSchemeGreen
        dark && s == "blue" -> darkSchemeBlue
        s == "blue" -> lightSchemeBlue
        dark && s == "violet" -> darkSchemeViolet
        s == "violet" -> lightSchemeViolet
        dark && s == "red" -> darkSchemeRed
        s == "red" -> lightSchemeRed
        dark && s == "pink" -> darkSchemePink
        s == "pink" -> lightSchemePink
        dark && s == "teal" -> darkSchemeTeal
        s == "teal" -> lightSchemeTeal
        dark && s == "amber" -> darkSchemeAmber
        s == "amber" -> lightSchemeAmber
        else -> lightSchemeCam
    }
}
